
GET  http://localhost:3002/api/customer/info HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTk4NzRhZjUwZGE2NjlmMzlhYzQ0NmQiLCJyb2xlIjoxLCJpYXQiOjE2Mzc0NjA4MDEsImV4cCI6MTYzNzU0NzIwMX0.6Kf4alJhn2VS9pP3e69Ul5v5_WJKJ7Dv9-A5NHMZnZE
###
GET  http://localhost:3002/api/customer HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTk4NzRhZjUwZGE2NjlmMzlhYzQ0NmQiLCJyb2xlIjoxLCJpYXQiOjE2Mzc0NjA4MDEsImV4cCI6MTYzNzU0NzIwMX0.6Kf4alJhn2VS9pP3e69Ul5v5_WJKJ7Dv9-A5NHMZnZE

###
POST  http://localhost:3002/api/customer/register HTTP/1.1
Content-Type: application/json

{
    "email":"lamtvu6@gmai.com",
    "phoneNumber":"123123123",
    "name":"lamtvu",
    "password":"123123123"
}

###
POST  http://localhost:3002/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "lamtvu3@gmai.com",
    "password":"123123123"
}

//-----------------------****Category****--------------------------------------
// --Create category
###
POST http://localhost:3000/api/category/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY0MzY5MTIsImV4cCI6MTYzNjUyMzMxMn0.iwBAHWxTduGnuKzex6PIT_PRxWhvR-MB1p0UVgdyUp8

{
    "name": "Casio3"
}

// delete category
###
DELETE  http://localhost:3000/api/category/delete/6184da0f7126ef5e8a1796d9 HTTP/1.1
Content-Type: application/json

// update category
###
PUT http://localhost:3002/api/category/update/61933609b339cfc58df55b5c HTTP/1.1
Content-Type: application/json

{
    "name": "rolex2"
}

// Get all category
###
GET http://localhost:3000/api/category/get-category HTTP/1.1
Content-Type: application/json

// Get category by id
###
GET http://localhost:3000/api/category/get-category/6184e50cff44164d7bc10975 HTTP/1.1
Content-Type: application/json

// -----------------***Producer***--------------------
###
POST http://localhost:3000/api/producer/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MTk3MTgsImV4cCI6MTYzNjgwNjExOH0.DZo_NFegE7QsQALaA3l6ydh-_3UMAk7PMbRN9Fth5Zs

{
    "name": "Apple"
}

// delete producer
###
DELETE  http://localhost:3000/api/producer/delete/618e5c843a3dbdca636004d2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MTk3MTgsImV4cCI6MTYzNjgwNjExOH0.DZo_NFegE7QsQALaA3l6ydh-_3UMAk7PMbRN9Fth5Zs

// update producer
###
PUT http://localhost:3000/api/producer/update/6184da0f7126ef5e8a1796d9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MTk3MTgsImV4cCI6MTYzNjgwNjExOH0.DZo_NFegE7QsQALaA3l6ydh-_3UMAk7PMbRN9Fth5Zs

{
    "name": "OppoWatch"
}

//get all producer
###
GET http://localhost:3000/api/producer/get-all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MTk3MTgsImV4cCI6MTYzNjgwNjExOH0.DZo_NFegE7QsQALaA3l6ydh-_3UMAk7PMbRN9Fth5Zs

// get producer by id
###
GET http://localhost:3000/api/producer/get-producer/618e5da43a3dbdca636004d5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MTk3MTgsImV4cCI6MTYzNjgwNjExOH0.DZo_NFegE7QsQALaA3l6ydh-_3UMAk7PMbRN9Fth5Zs


//---


//---------------------***Product***---------------------
//create product
###
POST http://localhost:3000/api/product/add HTTP/1.1
Content-Type: application/json

{
    "category": "6184da0f7126ef5e8a1796d9",
    "name": "casio",
    "description": "aaaaaaaaaaa",
    "detail": "bbbbbbbbbbbbbb",
    "image": "ccccccccccccccccc",
    "price": "500000"

}

// update product
###
PUT http://localhost:3000/api/product/update/6186236a6357dd68b200534b HTTP/1.1
Content-Type: application/json

{
    "category": "6184da0f7126ef5e8a1796d9",
    "name": "Casio2222",
    "description": "aaaaaaaaaaa",
    "detail": "bbbbbbbbbbbbbb",
    "image": "ccccccccccccccccc",
    "price": "500000"

}
/// Delete product
###
DELETE  http://localhost:3000/api/product/delete/61862499fc4ae53a8b9d0b87 HTTP/1.1
Content-Type: application/json

/// get all product
###
GET http://localhost:3000/api/product/get-all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY4NzkxNTYsImV4cCI6MTYzNjk2NTU1Nn0.ZpiDgm7ifT6EBCxHfQUoP6rYOVDX2wTLSI7LVODqOCs


/// get product by ID
###
GET http://localhost:3000/api/product/get-product/61862499fc4ae53a8b9d0b87 HTTP/1.1
Content-Type: application/json


///-------------------Discount--------------------

// create discount
###
POST http://localhost:3000/api/discount/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MjY0OTgsImV4cCI6MTYzNjgxMjg5OH0.5OcEegAyl3seRlonKfSA1jq-Clv2jdcFwGRGl-tshfY

{
    "products": ["61862499fc4ae53a8b9d0b87"],
    "value": 0.1,
    "endDate": 1637341200000

}

///-------------------------****Orders****---------------

//create order
###
POST http://localhost:3000/api/order/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MThhMGJhYTY0OGMzODBjZGExNDQyYjMiLCJyb2xlIjoxLCJpYXQiOjE2MzY3MjY0OTgsImV4cCI6MTYzNjgxMjg5OH0.5OcEegAyl3seRlonKfSA1jq-Clv2jdcFwGRGl-tshfY

{
    "orders":[{
        "product": "61862499fc4ae53a8b9d0b87",
        "count": 4
    },
    {
        "product": "618624ebfc4ae53a8b9d0b8a",
        "count": 3
    }],
    "address": "quận 1",
    "receiver": "hoang nam",
    "phoneReceiver": "0789687961"
}

// update order
###
PUT http://localhost:3000/api/order/update/6186291d19753482f4c4d23a HTTP/1.1
Content-Type: application/json

{
    "customer": "6184d793734083967795a2fe",
    "product": "61862499fc4ae53a8b9d0b87",
    "count": 3,
    "address": "thủ đức",
    "receiver": "hoang nam",
    "phoneReceiver": "0789687961",
    "totalPrice": 100000

}
// Delete order
###
DELETE  http://localhost:3000/api/order/delete/6186291d19753482f4c4d23a HTTP/1.1
Content-Type: application/json

// get all order
###
GET  http://localhost:3000/api/order/get-all HTTP/1.1
Content-Type: application/json

// get order by id
###
GET  http://localhost:3000/api/order/get-order/618629a819753482f4c4d23e HTTP/1.1
Content-Type: application/json